name: moomp

services:
  telnet:
    restart: always
    env_file: .env.deploy
    build:
      dockerfile: Dockerfile
    ports:
      - ${TELNET_PORT}:${TELNET_PORT}

  mongo:
    image: mongo
    restart: always
    env_file: .env.deploy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}

  mqtt:
    image: eclipse-mosquitto
    restart: always
    env_file: .env.deploy
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /docker/mosquitto/data
      - /docker/mosquitto/log
